# ----------------------------------------
# 1. LOGS (Requisitos de Registro de Atividades)
# ----------------------------------------
# Direciona os logs para a saída padrão (stdout/stderr) para o Docker/OTel capturarem
log_destination = 'stderr'

# Desliga o coletor interno para NÃO salvar logs em arquivos dentro do container
logging_collector = on

log_destination = 'stderr,jsonlog'
log_directory = 'log'
log_filename = 'postgresql.log'

# Define o que será logado (ajuste conforme a necessidade de auditoria)
# 'ddl' loga criação/alteração de tabelas. 'mod' loga inserts/updates. 'all' loga tudo.
log_statement = 'all'         # Não loga queries normais que deram certo
log_connections = off          # Não loga microserviços conectando
log_disconnections = off
pg_stat_statements.track = all

# 2. Ativa o pg_stat_activity (Monitoramento de conexões ativas em tempo real)
track_activities = on         # <--- ESTE COMPLEMENTA O ACTIVITY (Liga o monitor de comandos atuais)
track_counts = on             # Coleta estatísticas sobre atividade no banco
track_io_timing = on          # Mede o tempo de leitura/escrita de blocos de disco

# 3. Define o tamanho do texto da query que o activity consegue ler
track_activity_query_size = 1024

# Loga queries que demorarem mais de 250ms (ajuda a pegar gargalos antes do Grafana)
log_min_duration_statement = 500

log_min_messages = warning

# Só escreve o comando SQL no log se ele de fato gerar um ERRO.
log_min_error_statement = error

log_autovacuum_min_duration = 5000

# Altera o formato do log para incluir mais detalhes sobre conexões e usuários
log_line_prefix = '%m [%p] %q%u@%d '


# ----------------------------------------
# 2. EXTENSÕES & MÉTRICAS (Para pg_stat_statements)
# ----------------------------------------
# Pré-carrega a biblioteca de estatísticas de queries (Obrigatório)
shared_preload_libraries = 'pg_stat_statements'

# Rastreia todas as queries (incluindo as de dentro de funções/procedures)
pg_stat_statements.track = all

# Salva estatísticas de utilitários como VACUUM e COPY
pg_stat_statements.track_utility = on


# ----------------------------------------
# 3. MANUTENÇÃO AUTOMATIZADA (Item 11.a dos requisitos)
# ----------------------------------------
# Garante que o processo automático de limpeza e otimização esteja ativo
autovacuum = on

# Ajusta a agressividade do autovacuum se o banco tiver muita escrita
autovacuum_max_workers = 3
autovacuum_naptime = 1min

listen_addresses = '*'
port = 5432