events {}

http {

    upstream atelie_account_api {
        server app:8000;
    }

    upstream atelie_catalog_api {
        server catalog_api:8000;
    }

    upstream atelie_order_api {
        server order_api:8000;
    }

    upstream atelie_frontend {
        server frontend:80;
    }
    
    server {
        listen 443 ssl http2;
        server_name ateliedigital.dev.br;
    
        ssl_certificate     /etc/letsencrypt/live/ateliedigital.dev.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/ateliedigital.dev.br/privkey.pem;
    
        client_max_body_size 20m;
        proxy_http_version 1.1;
    
        location /api/v1/accounts/ {
            proxy_pass http://atelie_account_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location /admin/ {
            proxy_pass http://app:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location /api/v1/catalog/ {
            proxy_pass http://atelie_catalog_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location ~ ^/api/v1/(orders|carts|checkout|stores/orders) {
        	
            proxy_pass http://atelie_order_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location /audit/ {
            proxy_pass http://log_service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /media/ {
            proxy_pass http://minio:9000/; 
            
            proxy_set_header Host minio:9000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/staticfiles/;
        }

    
        location /otel/ {
            proxy_pass http://lgtm:3000; # Sem barra no final
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        
            # Suporte a WebSockets (necessário para recursos em tempo real do Grafana)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    
        location / {
            proxy_pass http://atelie_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name ateliedigital.dev.br;
    
        return 301 https://$host$request_uri;
    }
}
