# Generated by Django 6.0.2 on 2026-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='store/image')),
                ('banner', models.ImageField(upload_to='store/banner')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
